#!/bin/bash

cd /arget

aur () {
  curl -s --head https://aur.archlinux.org/packages/$pkg | head -n 1 | grep "HTTP/1.[01] [23].." > /dev/null
  if [ "$?" = "0" ]; then
    echo $pkg >> install.argt
    echo $pkg >> installtmp2.argt
    aur=1
  else
    aur=0
    
pkgbuilddep () {
  
