#!/bin/bash

cd /arget

aur () {
  curl -s --head https://aur.archlinux.org/packages/$pkg | head -n 1 | grep "HTTP/1.[01] [23].." > /dev/null
  if [ "$?" = "0" ]; then
    echo $pkg >> install.argt
    echo $pkg >> installtmp2.argt
    aur=1
  else
    aur=0
  fi
}
    
pkgbuilddep () {
 makepkg --printsrcinfo > srcinfo1.argt
 awk '/depend/' srcinfo1.argt > srcinfo2.argt
 awk '{ print $3 }' srcinfo2.argt > srcinfo3.argt
 sed 's/://' scrinfo3.argt > srcinfo.argt
 rm srcinfo1.argt
 rm srcinfo2.argt
 rm srcinfo3.argt
}
